name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Node
      - run: npm install

      - name: Set token
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: Set-Content -Path .\.env -Value $TOKEN

      - name: Run
        run: node src/app.js
