name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List directory
        run: ls -la
      - name: Add Discord Token
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: echo "TOKEN=$DISCORD_TOKEN" > .env
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          pull: true
