name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - shell: pwsh
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          Set-Content -Path .\.env -Value $TOKEN
      - run: node src/app.js
